# @host = https://api-stock-app.onrender.com

@host = http://localhost:4200

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoiNjgwYmJkMDdkZDVlZTEwZWM0NGVmMDdjIiwidXN1YXJpb19yb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDcxNTcyODh9.90isr79Z-5MRS0u5XJAk7NAviSjXQ-Od8DFAlbxvrVc

################
### USUARIOS ###
################

# Get All Users
GET {{host}}/api/users

### Get User by ID
GET {{host}}/api/users/680bbd07dd5ee10ec44ef07c
Authorization: Bearer {{token}}


### Register
POST {{host}}/api/users/register
Content-Type: application/json

{
    "name": "Admin0",
    "email": "admin@admin.com",
    "password": "123456",
    "role": "admin"
}

### Login
POST {{host}}/api/users/login
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "123456"
}

##########




################
### PRODUCTS ###
################

### Get All Products
GET {{host}}/api/products
Authorization: Bearer {{token}}

### Get Product by ID
GET {{host}}/api/products/680c9f4139ed74da59162187
Authorization: Bearer {{token}}

### Get Product By Barcode
GET {{host}}/api/products/barcode/SWINET882
Authorization: Bearer {{token}}

### Get Product Inventory Status
GET {{host}}/api/products/product-status/681145a01759154f47537012
Authorization: Bearer {{token}}

### Create Product
POST {{host}}/api/products
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "type": "Altacoz",
    "item": "Sonido LG 27",
    "stock": 1
}

### Update Product
PUT {{host}}/api/products/680c9f5339ed74da59162197
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "type": "AltavozTROTE",
    "item": "Sonido LG 27",
    "stock": 2
}

### Delete Product
DELETE {{host}}/api/products/680c9f4f39ed74da5916218f
Authorization: Bearer {{token}}




########################
### TRANSACCIONES ###
########################

### Crear transacción (sacar o guardar)
POST {{host}}/api/transactions
Authorization: Bearer {{token}}
Content-Type: application/jsonº

{
  "productId": "680c9eaa1759154f47537cfd",
  "type": "IN",
  "quantity": 1
}


### Obtener todas las transacciones
GET {{host}}/api/transactions
Authorization: Bearer {{token}}

### Obtener productos Out por usuario
GET {{host}}/api/transactions/user/681e12dba5f28d348016b870/out
Authorization: Bearer {{token}}

